# Generated by Django 3.0.6 on 2020-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickShop', '0008_auto_20200515_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='User123',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
